# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pixiv_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 375)
        MainWindow.setMinimumSize(QtCore.QSize(487, 375))
        MainWindow.setMaximumSize(QtCore.QSize(487, 375))
        MainWindow.setBaseSize(QtCore.QSize(487, 375))
        MainWindow.setToolTipDuration(0)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.GroupedDragging)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(384, 60, 91, 51))
        self.start.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.start.setAutoDefault(True)
        self.start.setObjectName("start")
        self.select_list = QtWidgets.QComboBox(self.centralwidget)
        self.select_list.setGeometry(QtCore.QRect(90, 20, 91, 22))
        self.select_list.setObjectName("select_list")
        self.select_list.addItem("")
        self.select_list.addItem("")
        self.select_list.addItem("")
        self.keywords_input = QtWidgets.QLineEdit(self.centralwidget)
        self.keywords_input.setGeometry(QtCore.QRect(190, 20, 81, 21))
        self.keywords_input.setObjectName("keywords_input")
        self.text_show = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_show.setGeometry(QtCore.QRect(20, 130, 451, 201))
        self.text_show.setAutoFillBackground(True)
        self.text_show.setObjectName("text_show")
        self.max_number = QtWidgets.QSpinBox(self.centralwidget)
        self.max_number.setGeometry(QtCore.QRect(90, 60, 51, 22))
        self.max_number.setMinimum(0)
        self.max_number.setMaximum(1000000)
        self.max_number.setProperty("value", 200)
        self.max_number.setObjectName("max_number")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 60, 81, 20))
        self.label_3.setObjectName("label_3")
        self.min_like = QtWidgets.QSpinBox(self.centralwidget)
        self.min_like.setGeometry(QtCore.QRect(230, 60, 51, 22))
        self.min_like.setMinimum(0)
        self.min_like.setMaximum(1000000)
        self.min_like.setObjectName("min_like")
        self.not_use_proxy = QtWidgets.QCheckBox(self.centralwidget)
        self.not_use_proxy.setGeometry(QtCore.QRect(300, 60, 91, 21))
        self.not_use_proxy.setObjectName("not_use_proxy")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 100, 54, 12))
        self.label_4.setObjectName("label_4")
        self.path = QtWidgets.QLineEdit(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(90, 100, 221, 20))
        self.path.setObjectName("path")
        self.path_buttom = QtWidgets.QPushButton(self.centralwidget)
        self.path_buttom.setGeometry(QtCore.QRect(320, 100, 41, 20))
        self.path_buttom.setChecked(False)
        self.path_buttom.setObjectName("path_buttom")
        self.for_single_dir = QtWidgets.QCheckBox(self.centralwidget)
        self.for_single_dir.setGeometry(QtCore.QRect(300, 20, 151, 20))
        self.for_single_dir.setObjectName("for_single_dir")
        self.up_date_speed = QtWidgets.QLabel(self.centralwidget)
        self.up_date_speed.setGeometry(QtCore.QRect(270, 340, 54, 12))
        self.up_date_speed.setObjectName("up_date_speed")
        self.download_speed = QtWidgets.QLabel(self.centralwidget)
        self.download_speed.setGeometry(QtCore.QRect(370, 340, 54, 12))
        self.download_speed.setObjectName("download_speed")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.path_buttom, self.start)
        MainWindow.setTabOrder(self.start, self.not_use_proxy)
        MainWindow.setTabOrder(self.not_use_proxy, self.min_like)
        MainWindow.setTabOrder(self.min_like, self.keywords_input)
        MainWindow.setTabOrder(self.keywords_input, self.select_list)
        MainWindow.setTabOrder(self.select_list, self.max_number)
        MainWindow.setTabOrder(self.max_number, self.path)
        MainWindow.setTabOrder(self.path, self.text_show)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pixiv_Downloader"))
        self.start.setText(_translate("MainWindow", "开始爬取"))
        self.select_list.setItemText(0, _translate("MainWindow", "画师id"))
        self.select_list.setItemText(1, _translate("MainWindow", "搜索结果"))
        self.select_list.setItemText(2, _translate("MainWindow", "每日排名"))
        self.label.setText(_translate("MainWindow", "爬取目标:"))
        self.label_2.setText(_translate("MainWindow", "限制数量:"))
        self.label_3.setText(_translate("MainWindow", "最少喜爱人数:"))
        self.not_use_proxy.setText(_translate("MainWindow", "免代理模式"))
        self.label_4.setText(_translate("MainWindow", "储存路径:"))
        self.path_buttom.setText(_translate("MainWindow", "..."))
        self.for_single_dir.setText(_translate("MainWindow", "为画册建立单独文件夹"))
        self.up_date_speed.setText(_translate("MainWindow", "TextLabel"))
        self.download_speed.setText(_translate("MainWindow", "TextLabel"))

